### ISSUE TITLE
Issue with Pie chart

### ISSUE THREAD

**Issue by swetha9676** [alexjj/PI-Vision-Custom-Symbols#1]
Hello,
In my system, the Pie chart is not working. Only a single color is displaying
![Pie chart issue](https://user-images.githubusercontent.com/32217664/59085669-0d32ca00-891d-11e9-8c87-cfc0a67d5c1f.JPG)
I am attaching one image file for reference..Please help me to solve this issue

**Comment by alexjj** [comment]
This repo is just a mirror of the OSIsoft’s one as they’ve taken down on of their repos recently. I suggest you post on their forum/developer’s community for [support](https://www.osisoft.com/support/)

**Comment by swetha9676** [comment]
Ok,ThankYou
